### ISSUE TITLE
Function fails to get input label name if label is assigned by nesting and not by for attribute

### ISSUE THREAD

**Issue by eetukomsi-avi** [qualweb/util#9]
HTML [specification ](https://html.spec.whatwg.org/multipage/forms.html#the-label-element)states that "If the for attribute is not specified, but the label element has a labelable element descendant, then the first such descendant in tree order is the label element's labeled control."

But 
[QualWeb's ACT test R16](https://github.com/qualweb/act-rules/blob/master/src/rules/QW-ACT-R16.ts) doesn't find the accessible name for input in a content structure described below
```
<div class="radio ">
    <label>
        <span>
            <input type="radio" name="x" required="" value="1">
            <span>labeltext</span>
        </span>
    </label>
</div>
```
Unclear whether this is beacause of the nesting structure or because the text value is located after the form element in question.

**Comment by carlosapaduarte** [comment]
Thanks for finding this @eetukomsi-avi 
It was an issue with the structure. More precisely, with the input element being a descendent but not a child of the label element.
Fix submitted in https://github.com/qualweb/qualweb/pull/164
